version: '3'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '8081:8081'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
